- src/app/projects/[projectId]/dependencies/page.tsx
- src/app/projects/[projectId]/page.tsx
- src/app/projects/page.tsx
- src/app/versions/[search]/page.tsx
- src/components/ui/data-table.tsx
- show lando local env with all selected envs
- switched table name and project column name
> feat: switching supabase db

- package-lock.json
- package.json
- src/components/ui/data-table.tsx
- src/components/ui/switch.tsx
- added shadcn switch
- added show lando switch on envs (beta, dev, prod)
> feat: show lando switch

- src/app/projects/[projectId]/columns.tsx
- src/app/versions/[search]/columns.tsx
- src/app/versions/[search]/page.tsx
- src/app/versions/page.tsx
- src/components/EndOfLifeCell.tsx
- src/components/LatestVersionCell.tsx
- src/components/ui/data-table.tsx
- src/constants/dependency-mappings.ts
- src/utils/utility-functions.ts
- fetch EOL date for the current version
- get latest version for the tech
- refactors and cleanups
> feat: end of life info and latest version

- src/components/EndOfLifeCell.tsx
- src/components/LatestVersionCell.tsx
- using tanstack query to cache 
- fix N/A being shown in destructive badge
- refactored End of Life pill to fetch a major version if 404 is encountered
> Caching and Refactors

- package-lock.json
- package.json
- src/components/EndOfLifeCell.tsx
- src/components/LatestVersionCell.tsx
- src/components/ui/tooltip.tsx
- added shadcn tooltip
- hovering on eol badge or latest version badge shows more info that was returned from the API
> Show more info on hover

- package-lock.json
- package.json
- src/app/page.tsx
- src/components/CurrentVersionTooltip.tsx
- src/components/EndOfLifeCell.tsx
- src/components/InfoTooltip.tsx
- src/components/LatestVersionCell.tsx
- src/components/ui/data-table.tsx
- new tooltip to show info about the current version
- new logic to figure out which version to fetch info for
- refactors and cleanups
> Better Tooltips

- src/components/EndOfLifeCell.tsx
- src/components/LatestVersionCell.tsx
- src/constants/dependency-mappings.ts
- figure out db and then get mariadb or mysql info
> Fetch DB Info

- src/app/dashboard/EOLDependenciesTable.tsx
- allow env selection
- count of EOL
> Dashboard updates

- src/app/api/basicauth/route.ts
- src/middleware.ts
- protect all routes except `/` and static image routes
> Basic HTTP Auth

- package-lock.json
- src/app/dashboard/EOLDependenciesTable.tsx
- src/app/projects/[projectId]/env/page.tsx
- src/app/projects/[projectId]/tools/page.tsx
- src/app/versions/TechnologyList.tsx
- src/app/versions/[search]/page.tsx
- src/app/versions/[search]/project/page.tsx
- src/components/CurrentVersionTooltip.tsx
- src/components/EndOfLifeCell.tsx
- src/components/InfoTooltip.tsx
- src/components/LatestVersionCell.tsx
- src/components/data-table.tsx
- src/components/project-tools-table.tsx
- src/components/project-versions-table.tsx
- refactor info versions tooltip
- replaced N/A with -
- refactor file locations
- new version side by side table
> Versions Side by Side

- src/components/EndOfLifeCell.tsx
- src/components/project-versions-table.tsx
- src/utils/utility-functions.ts
- add link to project from versions table
- updated date to relative dates
> Date & Link

- src/app/versions/log/page.tsx
> feat: latest data page

- src/components/DataCells.tsx
- src/components/Drupal11ReadinessTooltip.tsx
- src/components/InfoTooltip.tsx
- src/components/project-tools-table.tsx
- src/components/project-versions-table.tsx
- src/constants/dependency-mappings.ts
- added drupal 11 readiness key to versions list
- added new data cell to render out drupal 11 readiness info properly
- refactor existing table cell to its own component
> feat: drupal 11 readiness info

- .github/workflows/deploy.yml
- package-lock.json
- package.json
- src/app/actions/ActionsHomePage.tsx
- src/app/actions/page.tsx
- src/app/layout.tsx
- src/components/ActionCard.tsx
- src/components/ui/dropdown-menu.tsx
- src/components/ui/select.tsx
- src/components/ui/switch.tsx
- src/components/ui/table.tsx
- src/server-actions/github.ts
- tailwind.config.js
Fixes#[ZUINNOVATE-13](https://zucommunications.atlassian.net/browse/ZUINNOVATE-13)
- added tailwind scrollbar plugin
- removed ghAPI repo fetch. Fetching list of repositories from Supabase. 
- Removed over-scroll on all page.
[ZUINNOVATE-13]: https://zucommunications.atlassian.net/browse/ZUINNOVATE-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: added current actions view

- src/app/actions/ActionsHomePage.tsx
- added loading state and no actions found state indicators
> chore: add loading state

- src/app/actions/[repoName]/RepositoryActions.tsx
- src/components/skeletons/in-progress-actions-skeleton.tsx
- added filter dropdown for github actions
> feat: filter actions

- src/app/dashboard/SecurityAlertsTable.tsx
- src/app/dashboard/page.tsx
- src/app/security-alerts/layout.tsx
- src/app/security-alerts/page.tsx
- src/components/Header.tsx
- src/components/table-list-skeleton.tsx
- tsconfig.json
- new page to list all repos' open dependabot security alerts
> feat: security alerts page

- src/app/dashboard/SecurityAlertsTable.tsx
- src/components/table-list-skeleton.tsx
- feat: more info with tooltip
- added missing skeleton row
> improved security alerts page

- README.md
- src/app/page.tsx
- src/app/projects/[projectId]/tools/page.tsx
- src/components/card-with-link.tsx
- src/hooks/useFetchVersionData.ts
- added link to dependency-graph on GitHub
- always show card with links on a project page
- new feature card on the landing page 
- updated copy on the landing page
> project page updates

- package-lock.json
- package.json
- src/app/layout.tsx
- (analytics) :recycle: replace plausible with umami
> feat(analytics): :recycle: replace plausible with umami

- README.md
- database.types.ts
- package-lock.json
- package.json
- src/app/calendar/page.tsx
- src/app/dashboard/EOLDependenciesTable.tsx
- src/app/dashboard/page.tsx
- src/app/projects/[projectId]/tools/page.tsx
- src/app/versions/[search]/project/page.tsx
- src/app/versions/log/page.tsx
- src/components/project-tools-table.tsx
- src/components/project-versions-table.tsx
- src/constants/types.ts
- src/hooks/useProjectList.ts
- src/utils/supabase.ts
- supabase/.gitignore
- supabase/config.toml
- (supabase) :sparkles: auto gen db types
- (readme) :memo: supabase doc link
- (supabase) :sparkles: e2e type safety from supabase
- (npm) :sparkles: install supabase
> feat: ✨ supabase types

- package-lock.json
- package.json
- src/app/actions/[repoName]/RepositoryActions.tsx
- src/app/actions/[repoName]/teamMembers.ts
- src/app/layout.tsx
#Fixes[ZSW-11](https://zucommunications.atlassian.net/browse/ZSW-11).
- workflow runs can now be filtered by authorType and authorName
- added workflow runs' filtering
- (actions) :recycle: eslint and prettier changes
- (npm) :heavy_minus_sign: remove next-umami
- removed authorType filter
- added filter for human members
- Merge branch 'filter-actions' of github.com:ZuCommunications/dependency-tracker into filter-actions
> feat: added workflow runs' filtering

- next.config.ts
- src/app/actions/[repoName]/RepositoryActions.tsx
- (actions) :lipstick: added avatar to users
- switch to query state
> feat: user avatars in action author select dropdown

- src/hooks/useFetchTechData.ts
- src/hooks/useFetchVersionData.ts
- replace query with suspensequery
> fix: :bug: infinite loop
